package com.wangxiuwen.coursebox.core

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonElement
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.JsonPrimitive
import kotlinx.serialization.json.contentOrNull
import kotlinx.serialization.json.intOrNull
import kotlinx.serialization.json.jsonObject
import kotlinx.serialization.json.jsonPrimitive

/**
 * Course-package wire format — mirrors lib/course_package.dart from the
 * Flutter version. Generated by scripts/package_*.py and packed into a zip
 * alongside `objects/<sha256>.<ext>` resources.
 *
 *     manifest.json
 *     objects/<sha256>.json   # lessons detail
 *     objects/<sha256>.mp3    # one per audio resource
 *     objects/<sha256>.pdf    # music sheets etc
 */
@Serializable
data class CourseResource(
    val hash: String,                       // "sha256:..."
    val path: String,                       // "objects/<sha>.ext" inside the zip
    val size: Long = 0L,
    val type: String = "application/octet-stream",
    val origin: String = "",                // original logical path, e.g. "nce-mp3/2/lesson1.mp3"
    val tags: List<String> = emptyList(),
)

@Serializable
data class LessonIndexEntry(
    val id: String,
    val title: String = "",
    val subtitle: String = "",
    @SerialName("audio_hash") val audioHash: String = "",
    @SerialName("video_hash") val videoHash: String = "",
    val tags: List<String> = emptyList(),
    val metadata: Map<String, JsonElement> = emptyMap(),
) {
    val book: Int? get() = (metadata["book"] as? JsonPrimitive)?.intOrNull
    val lesson: Int? get() = (metadata["lesson"] as? JsonPrimitive)?.intOrNull
    val isVideo: Boolean get() = videoHash.isNotBlank()
}

@Serializable
data class CourseEntry(
    val id: String,
    val title: String,
    val description: String = "",
    val type: String = "audio_course",       // nce / chinese_poetry / music / audio_course
    @SerialName("lessons_manifest") val lessonsManifest: String,
    @SerialName("lesson_index") val lessonIndex: List<LessonIndexEntry> = emptyList(),
    val metadata: Map<String, JsonElement> = emptyMap(),
)

@Serializable
data class CoursePackageManifest(
    val format: String,
    val version: Int,
    @SerialName("generated_at") val generatedAt: String = "",
    val generator: String = "",
    val resources: List<CourseResource> = emptyList(),
    val courses: List<CourseEntry> = emptyList(),
    /** When the pack was split by the packager because it would exceed
     *  `--max-part-bytes`, this lists every part filename in order
     *  (e.g. ["name.cx.part0", "name.cx.part1", ...]). Absent for
     *  single-file packs. */
    @SerialName("multipart_parts") val multipartParts: List<String> = emptyList(),
)

/**
 * Installed/imported package record persisted in library_index.json.
 * `lessonsManifestPath` is an absolute path on disk; `resourceIndex` maps
 * sha256 → absolute path; `logicalPathIndex` maps the original "origin"
 * path (e.g. "poetry/tangshi300.json", with "assets/" prefix stripped) →
 * absolute path, so legacy callers that reference assets-style paths still
 * resolve.
 */
@Serializable
data class CoursePackageRecord(
    val id: String,
    val title: String,
    val description: String = "",
    val type: String = "audio_course",
    val metadata: Map<String, JsonElement> = emptyMap(),
    @SerialName("lessons_manifest_path") val lessonsManifestPath: String,
    @SerialName("lesson_index") val lessonIndex: List<LessonIndexEntry> = emptyList(),
    /** sha256 → `cx://` URI into the backing .cx (or one of its .partN). */
    @SerialName("resource_index") val resourceIndex: Map<String, String> = emptyMap(),
    @SerialName("logical_path_index") val logicalPathIndex: Map<String, String> = emptyMap(),
    @SerialName("imported_at") val importedAt: String = "",
    val source: String = "",
    /** Every .cx file backing this record. Single-part packs have one
     *  entry; multi-part packs grow this list as each partN is imported. */
    @SerialName("cx_paths") val cxPaths: List<String> = emptyList(),
    /** Filenames of the parts the packager declared up-front (from
     *  manifest.multipart_parts). Empty for single-part packs. Used at
     *  import time to find which package an arriving partN belongs to. */
    @SerialName("multipart_parts") val multipartParts: List<String> = emptyList(),
)

@Serializable
data class CourseLibraryState(
    val packages: List<CoursePackageRecord> = emptyList(),
    val learning: Set<String> = emptySet(),
    /** Pinned course ids — order matters (most recent pin first). */
    val pinned: List<String> = emptyList(),
)

/** Normalize a logical path so writer and reader agree. */
fun normalizeLogicalPath(raw: String): String {
    var p = raw.replace('\\', '/').trim()
    if (p.startsWith("./")) p = p.substring(2)
    if (p.startsWith("assets/")) p = p.substring("assets/".length)
    while (p.startsWith("/")) p = p.substring(1)
    return p
}

internal fun JsonObject.stringOrEmpty(key: String): String =
    (this[key] as? JsonPrimitive)?.contentOrNull ?: ""
